apiVersion: v1
kind: Service
metadata:
  name: postgrest
  labels:
    shaple.io/project.name: "{{ .Project.Name | toLabel }}"
    shaple.io/stack.name: "{{ .Stack.Name | toLabel }}"
    shaple.io/component: postgrest
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
  namespace: "{{ .Stack.Namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
    - port: 3001
      name: admin
  selector:
    shaple.io/component: postgrest
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
