apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Stack.Namespace }}
  labels:
    shaple.io/project.name: "{{ .Project.Name | toLabel }}"
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.name: "{{ .Stack.Name | toLabel }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
    shaple.io/component: auth
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
    shaple.io/component: auth
