apiVersion: v1
kind: ConfigMap
metadata:
  name: common
  namespace: "{{ .Stack.Namespace }}"
  labels:
    shaple.io/project.name: "{{ $.Project.Name | toLabel }}"
    shaple.io/project.id: "{{ $.Project.ID }}"
    shaple.io/stack.name: "{{ $.Stack.Name | toLabel }}"
    shaple.io/stack.id: "{{ $.Stack.ID }}"
    shaple.io/component: common
data:
  _vapi_main.ts: |
    {{ vapiMainFile | nindent 4 }}