apiVersion: v1
kind: Secret
metadata:
  name: storage
  namespace: {{ .Stack.Namespace }}
  labels:
    shaple.io/project.name: "{{ .Project.Name | toLabel }}"
    shaple.io/stack.name: "{{ .Stack.Name | toLabel }}"
    shaple.io/component: storage
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
type: Opaque
data:
  aws_access_key: "{{ .Storage.S3.AccessKey | b64enc }}"
  aws_secret_key: "{{ .Storage.S3.SecretKey | b64enc }}"
  anon_key: "{{ .Stack.AnonApiKey | b64enc }}"
  service_key: "{{ .Stack.AdminApiKey | b64enc }}"