apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: {{ .Stack.Namespace }}
  labels:
    shaple.io/project.name: "{{ .Project.Name | toLabel }}"
    shaple.io/stack.name: "{{ .Stack.Name | toLabel }}"
    shaple.io/component: storage
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    shaple.io/component: storage
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"

