{{- range $index, $vapi := .CustomVapis }}
{{- if ne $index 0}}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: custom-vapi-{{ $vapi.ID }}
  namespace: {{ $.Stack.Namespace }}
  labels:
    shaple.io/project.name: "{{ $.Project.Name | toLabel }}"
    shaple.io/project.id: "{{ $.Project.ID }}"
    shaple.io/stack.name: "{{ $.Stack.Name | toLabel }}"
    shaple.io/stack.id: "{{ $.Stack.ID }}"
    shaple.io/component: custom-vapi
    shaple.io/vapi.id: "{{ $vapi.ID }}"
type: Opaque
data:
  SHAPLE_ANON_KEY: "{{ $.Stack.AnonApiKey | b64enc }}"
  SHAPLE_ADMIN_KEY: "{{ $.Stack.AdminApiKey | b64enc }}"
  {{- range $key, $secret := $vapi.EnvVars }}
  {{ $key }}: "{{ $secret | b64enc }}"
  {{- end }}
{{- end }}