apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: "{{ .Stack.Namespace }}"
  labels:
    shaple.io/project.name: "{{ .Project.Name | toLabel }}"
    shaple.io/stack.name: "{{ .Stack.Name | toLabel }}"
    shaple.io/component: database
    shaple.io/project.id: "{{ .Project.ID }}"
    shaple.io/stack.id: "{{ .Stack.ID }}"
type: Opaque
data:
  db_username: "{{ .DB.Username | b64enc }}"
  db_password: "{{ .DB.Password | b64enc }}"
  db_name: "{{ .DB.Name | b64enc }}"